version: 0.0
os: linux
files: 
  - source: /routes
    destination: /home/ec2-user/aws-cicd-test/routes
  - source: /package.json
    destination: /home/ec2-user/aws-cicd-test/package.json
  - source: /app.js
    destination: /home/ec2-user/aws-cicd-test/app.js

hooks:
  BeforeInstall:
    - location: deployment_scripts/prepare.sh
      runas: ec2-user
  AfterInstall:
    - location: deployment_scripts/deploy.sh
      runas: ec2-user
  ApplicationStart:
    - location: deployment_scripts/start.sh
      runas: ec2-user
