version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/aws-cicd-test/

hooks:
  ApplicationStop:
    - location: deployment_scripts/stop.sh
  BeforeInstall:
    - location: deployment_scripts/prepare.sh
  AfterInstall:
    - location: deployment_scripts/deploy.sh
  ApplicationStart:
    - location: deployment_scripts/start.sh
