version: 0.0
os: linux
files: 
  - source: /routes
    destination: /home/ec2-user/aws-cicd-test/routes
  - source: /package.json
    destination: /home/ec2-user/aws-cicd-test/
  - source: /app.js
    destination: /home/ec2-user/aws-cicd-test/

permissions:
    - object: /home/ec2-user/aws-cicd-test
      pattern: "**"
      owner: ec2-user
      group: ec2-user
      mode: 755
      type:
        - file

hooks:
  BeforeInstall:
    - location: deployment_scripts/prepare.sh
      runas: ec2-user
  AfterInstall:
    - location: deployment_scripts/deploy.sh
      runas: ec2-user
  ApplicationStart:
    - location: deployment_scripts/start.sh
      runas: ec2-user
