version: 0.0
os: linux
files: 
  - source: /routes
    destination: /home/ec2-user/aws-cicd-test/routes
  - source: /package.json
    destination: /home/ec2-user/aws-cicd-test/package.json

hooks:
  ApplicationStop:
    - location: deployment_scripts/stop.sh
#  BeforeInstall:
#    - location: deployment_scripts/prepare.sh
  AfterInstall:
    - location: deployment_scripts/deploy.sh
  ApplicationStart:
    - location: deployment_scripts/start.sh
