version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm test

artifacts:
    files: 
      - app.js
      - routes/*
      - package.json
      - appspec.yml
      - deployment_scripts/*
